### ISSUE TITLE
Mac version 5529 - no setting for removing the 2 first Dashboard panels

### ISSUE THREAD

**Issue by jpdup** [MylioExternal/bugs#29]
![image](https://user-images.githubusercontent.com/2709213/48635907-4d7d2b80-e97e-11e8-9dde-40569a23fabe.png)

![image](https://user-images.githubusercontent.com/2709213/48635852-2888b880-e97e-11e8-9d21-f31ff12e6f5c.png)

**Comment by mylodeon** [comment]
It's there:

![image](https://user-images.githubusercontent.com/6981366/48637117-8ff43780-e981-11e8-84eb-186379f74cf7.png)

Switch to dev mode if you're not seeing them.

**Comment by jpdup** [comment]
Are you saying that this feature is only available in Dev mode.  Real customer are forced to endure those two first panels?
